AWSTemplateFormatVersion: 2010-09-09
Description: Creates an S3 bucket with the bucket name hardcoded

Resources: 
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicRead
      BucketName: www.domain.com