AWSTemplateFormatVersion: 2010-09-09
Description: Creates an S3 bucket with the website name hardcoded. Configures the bucket for static hosting.

Resources: 
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: www.domain.com
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html
  s3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 
        Ref: s3Bucket
      PolicyDocument:
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Principal: '*'
          Resource:
            Fn::Sub: arn:aws:s3:::${s3Bucket}/*
          Sid: WebSiteBucketReadAccess