AWSTemplateFormatVersion: 2010-09-09
Description: Creates an S3 bucket with the website name passed as a parameter. Configures the bucket for static hosting.

Parameters:
  Website:
    Default: example.com
    Description: Please enter the website name. Bare domain only. Do not enter http/https and www
    Type: String
Resources: 
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Fn::Sub: www.${Website}
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html
  s3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 
        Ref: s3Bucket
      PolicyDocument:
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Principal: '*'
          Resource:
            Fn::Sub: arn:aws:s3:::${s3Bucket}/*
          Sid: WebSiteBucketReadAccess